// templates/templateConfig.js - COMPLETE Template Database

// Import constants
import {
    TemplateCategories,
    TemplateCategoryKeys,
    ImageMimeTypes,
    FileExtensions,
    AspectRatios
} from '../constants/sharedConstants.js';

// ===== COMPLETE TEMPLATE DATABASE =====
export const LemGendTemplates = {
    ALL: [
        // === FAVICON TEMPLATES ===
        {
            id: 'favicon-basic',
            displayName: 'Basic Favicon',
            width: '16px',
            height: '16px',
            category: TemplateCategories.FAVICON,
            recommendedFormats: [FileExtensions.ICO, FileExtensions.PNG],
            platforms: ['web', 'browser'],
            commonUses: ['website-icon', 'browser-tab'],
            requiresCrop: true,
            minWidth: 16,
            minHeight: 16,
            description: 'Standard 16×16 favicon for browser tabs',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '1KB',
            notes: 'Required for most browsers, displays in browser tabs',
            supportsFlexible: false
        },
        {
            id: 'favicon-standard',
            displayName: 'Standard Favicon Set',
            width: '32px',
            height: '32px',
            category: TemplateCategories.FAVICON,
            recommendedFormats: [FileExtensions.ICO],
            platforms: ['web', 'browser'],
            commonUses: ['website-icon', 'browser-tab'],
            requiresCrop: true,
            minWidth: 32,
            minHeight: 32,
            description: 'Standard favicon set for desktop browsers',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '10KB',
            notes: 'Includes 16×16, 32×32, 48×48 sizes in single .ico file',
            supportsFlexible: false
        },
        {
            id: 'favicon-modern',
            displayName: 'Modern Favicon Set',
            width: '180px',
            height: '180px',
            category: TemplateCategories.FAVICON,
            recommendedFormats: [FileExtensions.PNG, FileExtensions.SVG],
            platforms: ['web', 'browser', 'mobile'],
            commonUses: ['website-icon', 'pwa', 'mobile'],
            requiresCrop: true,
            minWidth: 180,
            minHeight: 180,
            description: 'Complete favicon set for all modern devices',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '30KB',
            notes: 'Includes iOS home screen, Android, Safari pinned tab, Windows tile',
            supportsFlexible: false
        },
        {
            id: 'favicon-apple',
            displayName: 'Apple Touch Icon',
            width: '180px',
            height: '180px',
            category: TemplateCategories.FAVICON,
            recommendedFormats: [FileExtensions.PNG],
            platforms: ['ios', 'mobile'],
            commonUses: ['mobile-app', 'home-screen'],
            requiresCrop: true,
            minWidth: 180,
            minHeight: 180,
            description: 'Apple devices home screen icon',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '20KB',
            notes: 'For iOS devices when saving to home screen',
            supportsFlexible: false
        },
        {
            id: 'favicon-android',
            displayName: 'Android Chrome Icon',
            width: '192px',
            height: '192px',
            category: TemplateCategories.FAVICON,
            recommendedFormats: [FileExtensions.PNG],
            platforms: ['android', 'mobile'],
            commonUses: ['mobile-app', 'home-screen'],
            requiresCrop: true,
            minWidth: 192,
            minHeight: 192,
            description: 'Android Chrome home screen icon',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '20KB',
            notes: 'For Android devices when saving to home screen',
            supportsFlexible: false
        },
        {
            id: 'favicon-safari',
            displayName: 'Safari Pinned Tab',
            width: '16px',
            height: '16px',
            category: TemplateCategories.FAVICON,
            recommendedFormats: [FileExtensions.SVG],
            platforms: ['safari', 'browser'],
            commonUses: ['website-icon', 'pinned-tab'],
            requiresCrop: true,
            minWidth: 16,
            minHeight: 16,
            description: 'SVG icon for Safari pinned tabs',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '5KB',
            notes: 'Monochrome SVG for Safari pinned tabs feature',
            supportsFlexible: false
        },
        {
            id: 'favicon-windows',
            displayName: 'Windows Tile',
            width: '144px',
            height: '144px',
            category: TemplateCategories.FAVICON,
            recommendedFormats: [FileExtensions.PNG],
            platforms: ['windows', 'desktop'],
            commonUses: ['windows-app', 'start-menu'],
            requiresCrop: true,
            minWidth: 144,
            minHeight: 144,
            description: 'Windows 8/10 start menu tile icon',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '15KB',
            notes: 'For Windows devices when pinning to start menu',
            supportsFlexible: false
        },
        {
            id: 'favicon-retina',
            displayName: 'Retina Favicon',
            width: '64px',
            height: '64px',
            category: TemplateCategories.FAVICON,
            recommendedFormats: [FileExtensions.PNG, FileExtensions.ICO],
            platforms: ['web', 'browser', 'retina'],
            commonUses: ['website-icon', 'high-dpi'],
            requiresCrop: true,
            minWidth: 64,
            minHeight: 64,
            description: 'High-resolution favicon for retina displays',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '15KB',
            notes: 'For high-DPI screens, includes @2x and @3x versions',
            supportsFlexible: false
        },
        {
            id: 'favicon-complete',
            displayName: 'Complete Favicon Package',
            width: '512px',
            height: '512px',
            category: TemplateCategories.FAVICON,
            recommendedFormats: [FileExtensions.ICO, FileExtensions.PNG, FileExtensions.SVG],
            platforms: ['web', 'browser', 'mobile', 'desktop'],
            commonUses: ['website-icon', 'complete-package'],
            requiresCrop: true,
            minWidth: 512,
            minHeight: 512,
            description: 'Complete favicon package with all necessary sizes',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '50KB',
            notes: 'Includes all sizes: 16×16, 32×32, 48×48, 64×64, 128×128, 180×180, 192×192, 256×256, 512×512',
            supportsFlexible: true
        },

        // === LOGO TEMPLATES ===
        {
            id: 'logo-rectangular',
            displayName: 'Rectangular Logo',
            width: '300px',
            height: '150px',
            category: TemplateCategories.LOGO,
            recommendedFormats: [FileExtensions.PNG, FileExtensions.SVG],
            platforms: ['web', 'print', 'email'],
            commonUses: ['website-header', 'email-signature', 'documentation'],
            requiresCrop: true,
            minWidth: 300,
            minHeight: 150,
            description: 'Standard rectangular logo format',
            aspectRatio: '2:1',
            maxSize: '50KB',
            notes: 'Good for website headers and email signatures',
            supportsFlexible: false
        },
        {
            id: 'logo-square',
            displayName: 'Square Logo',
            width: '500px',
            height: '500px',
            category: TemplateCategories.LOGO,
            recommendedFormats: [FileExtensions.PNG, FileExtensions.SVG],
            platforms: ['social', 'web', 'mobile'],
            commonUses: ['social-media', 'mobile-app', 'profile'],
            requiresCrop: true,
            minWidth: 500,
            minHeight: 500,
            description: 'Square logo for social media and apps',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '50KB',
            notes: 'Required for many social media platforms',
            supportsFlexible: false
        },
        {
            id: 'logo-print',
            displayName: 'Print-Ready Logo',
            width: '3000px',
            height: '3000px',
            category: TemplateCategories.LOGO,
            recommendedFormats: [FileExtensions.PNG, FileExtensions.SVG, FileExtensions.PDF, 'eps'],
            platforms: ['print'],
            commonUses: ['business-card', 'brochure', 'signage'],
            requiresCrop: true,
            minWidth: 3000,
            minHeight: 3000,
            description: 'High-resolution logo for print materials',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '2MB',
            notes: '300 DPI minimum for quality printing',
            supportsFlexible: false
        },
        {
            id: 'logo-watermark',
            displayName: 'Watermark',
            width: '1000px',
            height: '400px',
            category: TemplateCategories.LOGO,
            recommendedFormats: [FileExtensions.PNG],
            platforms: ['photo', 'video'],
            commonUses: ['photo-protection', 'branding', 'video-overlay'],
            requiresCrop: true,
            minWidth: 1000,
            minHeight: 400,
            description: 'Semi-transparent watermark for photos',
            aspectRatio: '2.5:1',
            maxSize: '50KB',
            notes: 'Use PNG with transparency for overlay',
            supportsFlexible: false
        },
        {
            id: 'logo-vertical',
            displayName: 'Vertical Logo',
            width: '500px',
            height: '800px',
            category: TemplateCategories.LOGO,
            recommendedFormats: [FileExtensions.PNG, FileExtensions.SVG],
            platforms: ['mobile', 'documentation'],
            commonUses: ['mobile-app', 'document-header', 'presentation'],
            requiresCrop: true,
            minWidth: 500,
            minHeight: 800,
            description: 'Tall logo for vertical spaces',
            aspectRatio: AspectRatios.TWO_THREE,
            maxSize: '50KB',
            notes: 'Good for mobile apps and documentation',
            supportsFlexible: false
        },

        // === SOCIAL MEDIA TEMPLATES ===
        // Facebook
        {
            id: 'facebook-profile',
            displayName: 'Facebook Profile Picture',
            width: '180px',
            height: '180px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['facebook'],
            commonUses: ['profile', 'avatar'],
            requiresCrop: true,
            minWidth: 180,
            minHeight: 180,
            description: 'Facebook profile picture (displays as 170×170 on desktop)',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '5MB',
            notes: 'Minimum 180×180, displays as circular',
            supportsFlexible: false
        },
        {
            id: 'facebook-cover',
            displayName: 'Facebook Cover Photo',
            width: '851px',
            height: '315px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['facebook'],
            commonUses: ['cover', 'banner'],
            requiresCrop: true,
            minWidth: 851,
            minHeight: 315,
            description: 'Facebook page and profile cover photo',
            aspectRatio: '~2.7:1',
            maxSize: '100KB',
            notes: 'Displays as 820×312 on desktop, mobile crops sides',
            supportsFlexible: false
        },
        {
            id: 'facebook-shared',
            displayName: 'Facebook Shared Image',
            width: '1200px',
            height: '630px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['facebook'],
            commonUses: ['shared-post', 'link-preview'],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 630,
            description: 'Optimal size for shared links and images in feed',
            aspectRatio: '1.91:1',
            maxSize: '8MB',
            notes: 'Ideal for link previews and engagement',
            supportsFlexible: false
        },
        {
            id: 'facebook-square',
            displayName: 'Facebook Square Post',
            width: '1200px',
            height: '1200px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['facebook'],
            commonUses: ['feed-post', 'album'],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 1200,
            description: 'Facebook square post images',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '8MB',
            notes: 'Good for product shots and albums',
            supportsFlexible: false
        },
        {
            id: 'facebook-stories',
            displayName: 'Facebook Stories',
            width: '1080px',
            height: '1920px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['facebook'],
            commonUses: ['stories'],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1920,
            description: 'Facebook Stories (full-screen vertical)',
            aspectRatio: '9:16',
            maxSize: '4MB',
            notes: 'Same as Instagram Stories format',
            supportsFlexible: false
        },

        // Instagram
        {
            id: 'instagram-profile',
            displayName: 'Instagram Profile Picture',
            width: '320px',
            height: '320px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.WEBP],
            platforms: ['instagram'],
            commonUses: ['profile', 'avatar'],
            requiresCrop: true,
            minWidth: 320,
            minHeight: 320,
            description: 'Instagram profile picture (displays as circular 110×110 in app)',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '100KB',
            notes: 'Upload at 320×320 for best quality, will be cropped to circle',
            supportsFlexible: false
        },
        {
            id: 'instagram-square',
            displayName: 'Instagram Square Post',
            width: '1080px',
            height: '1080px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.WEBP],
            platforms: ['instagram'],
            commonUses: ['social-media', 'feed-post'],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1080,
            description: 'Instagram square photo/video posts',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '8MB',
            notes: 'Optimal for grid view, displays at 600×600',
            supportsFlexible: false
        },
        {
            id: 'instagram-portrait',
            displayName: 'Instagram Portrait Post',
            width: '1080px',
            height: '1350px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.WEBP],
            platforms: ['instagram'],
            commonUses: ['social-media', 'feed-post'],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1350,
            description: 'Instagram portrait (vertical) posts',
            aspectRatio: AspectRatios.THREE_FOUR,
            maxSize: '8MB',
            notes: 'Takes more space in feed, good for full-body shots',
            supportsFlexible: false
        },
        {
            id: 'instagram-landscape',
            displayName: 'Instagram Landscape Post',
            width: '1080px',
            height: '566px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.WEBP],
            platforms: ['instagram'],
            commonUses: ['social-media', 'feed-post'],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 566,
            description: 'Instagram landscape (horizontal) posts',
            aspectRatio: '1.91:1',
            maxSize: '8MB',
            notes: 'Good for group photos and scenery',
            supportsFlexible: false
        },
        {
            id: 'instagram-stories',
            displayName: 'Instagram Stories & Reels',
            width: '1080px',
            height: '1920px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.WEBP],
            platforms: ['instagram'],
            commonUses: ['stories', 'reels', 'igtv'],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1920,
            description: 'Instagram Stories, Reels, and IGTV covers',
            aspectRatio: '9:16',
            maxSize: '4MB',
            notes: 'Full-screen vertical format, safe area: center 1080×1420',
            supportsFlexible: false
        },

        // Twitter/X
        {
            id: 'twitter-profile',
            displayName: 'Twitter/X Profile Picture',
            width: '400px',
            height: '400px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['twitter'],
            commonUses: ['profile', 'avatar'],
            requiresCrop: true,
            minWidth: 400,
            minHeight: 400,
            description: 'Twitter/X profile picture (displays as 200×200)',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '2MB',
            notes: 'Upload at 400×400, displays as circular',
            supportsFlexible: false
        },
        {
            id: 'twitter-header',
            displayName: 'Twitter/X Header Banner',
            width: '1500px',
            height: '500px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['twitter'],
            commonUses: ['header', 'banner'],
            requiresCrop: true,
            minWidth: 1500,
            minHeight: 500,
            description: 'Twitter/X header banner',
            aspectRatio: '3:1',
            maxSize: '5MB',
            notes: 'Minimum 1500×500, important content in center',
            supportsFlexible: false
        },
        {
            id: 'twitter-landscape',
            displayName: 'Twitter/X Landscape Post',
            width: '1600px',
            height: '900px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['twitter'],
            commonUses: ['tweet', 'screenshot'],
            requiresCrop: true,
            minWidth: 1600,
            minHeight: 900,
            description: 'Twitter/X landscape image in tweet',
            aspectRatio: AspectRatios.SIXTEEN_NINE,
            maxSize: '5MB',
            notes: 'Optimal for screenshots and wide images',
            supportsFlexible: false
        },
        {
            id: 'twitter-square',
            displayName: 'Twitter/X Square Post',
            width: '1080px',
            height: '1080px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['twitter'],
            commonUses: ['tweet', 'product-image'],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1080,
            description: 'Twitter/X square image in tweet',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '5MB',
            notes: 'Good for product images and infographics',
            supportsFlexible: false
        },
        {
            id: 'twitter-portrait',
            displayName: 'Twitter/X Portrait Post',
            width: '1080px',
            height: '1350px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['twitter'],
            commonUses: ['tweet', 'portrait-image'],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1350,
            description: 'Twitter/X portrait (vertical) image',
            aspectRatio: AspectRatios.THREE_FOUR,
            maxSize: '5MB',
            notes: 'Similar to Instagram portrait format',
            supportsFlexible: false
        },

        // LinkedIn
        {
            id: 'linkedin-profile',
            displayName: 'LinkedIn Profile Picture',
            width: '400px',
            height: '400px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['linkedin'],
            commonUses: ['profile', 'avatar'],
            requiresCrop: true,
            minWidth: 400,
            minHeight: 400,
            description: 'LinkedIn profile picture (displays as circular)',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '8MB',
            notes: 'Upload at 400×400, minimum 300×300',
            supportsFlexible: false
        },
        {
            id: 'linkedin-cover',
            displayName: 'LinkedIn Personal Cover Photo',
            width: '1584px',
            height: '396px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['linkedin'],
            commonUses: ['cover', 'banner'],
            requiresCrop: true,
            minWidth: 1584,
            minHeight: 396,
            description: 'LinkedIn personal profile cover photo',
            aspectRatio: '4:1',
            maxSize: '8MB',
            notes: 'Displays as 1400×425, keep important content centered',
            supportsFlexible: false
        },
        {
            id: 'linkedin-landscape',
            displayName: 'LinkedIn Landscape Post',
            width: '1200px',
            height: '627px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['linkedin'],
            commonUses: ['post', 'article'],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 627,
            description: 'LinkedIn landscape post images',
            aspectRatio: '1.91:1',
            maxSize: '5MB',
            notes: 'Optimal for shared links and articles',
            supportsFlexible: false
        },
        {
            id: 'linkedin-square',
            displayName: 'LinkedIn Square Post',
            width: '1200px',
            height: '1200px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['linkedin'],
            commonUses: ['post', 'infographic'],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 1200,
            description: 'LinkedIn square post images',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '5MB',
            notes: 'Good for infographics and product images',
            supportsFlexible: false
        },
        {
            id: 'linkedin-portrait',
            displayName: 'LinkedIn Portrait Post',
            width: '720px',
            height: '900px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['linkedin'],
            commonUses: ['post', 'vertical-image'],
            requiresCrop: true,
            minWidth: 720,
            minHeight: 900,
            description: 'LinkedIn portrait (vertical) post images',
            aspectRatio: AspectRatios.THREE_FOUR,
            maxSize: '5MB',
            notes: 'Less common but supported format',
            supportsFlexible: false
        },

        // YouTube
        {
            id: 'youtube-channel',
            displayName: 'YouTube Channel Icon',
            width: '800px',
            height: '800px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['youtube'],
            commonUses: ['profile', 'channel-icon'],
            requiresCrop: true,
            minWidth: 800,
            minHeight: 800,
            description: 'YouTube channel profile picture',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '2MB',
            notes: 'Displays as 98×98 in most places',
            supportsFlexible: false
        },
        {
            id: 'youtube-banner',
            displayName: 'YouTube Channel Banner',
            width: '2048px',
            height: '1152px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['youtube'],
            commonUses: ['banner', 'channel-art'],
            requiresCrop: true,
            minWidth: 2048,
            minHeight: 1152,
            description: 'YouTube channel banner/header',
            aspectRatio: AspectRatios.SIXTEEN_NINE,
            maxSize: '6MB',
            notes: 'Safe area for mobile: 1546×423, important content centered',
            supportsFlexible: false
        },
        {
            id: 'youtube-thumbnail',
            displayName: 'YouTube Video Thumbnail',
            width: '1280px',
            height: '720px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['youtube'],
            commonUses: ['thumbnail', 'video-preview'],
            requiresCrop: true,
            minWidth: 1280,
            minHeight: 720,
            description: 'YouTube video thumbnail',
            aspectRatio: AspectRatios.SIXTEEN_NINE,
            maxSize: '2MB',
            notes: 'Minimum 640×480, 16:9 recommended for all devices',
            supportsFlexible: false
        },

        // Pinterest
        {
            id: 'pinterest-profile',
            displayName: 'Pinterest Profile Picture',
            width: '165px',
            height: '165px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['pinterest'],
            commonUses: ['profile', 'avatar'],
            requiresCrop: true,
            minWidth: 165,
            minHeight: 165,
            description: 'Pinterest profile picture (displays as circular)',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '10MB',
            notes: 'Upload at 165×165, displays as circular',
            supportsFlexible: false
        },
        {
            id: 'pinterest-standard',
            displayName: 'Pinterest Standard Pin',
            width: '1000px',
            height: '1500px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['pinterest'],
            commonUses: ['pin', 'vertical-image'],
            requiresCrop: true,
            minWidth: 1000,
            minHeight: 1500,
            description: 'Pinterest standard vertical pin',
            aspectRatio: AspectRatios.TWO_THREE,
            maxSize: '10MB',
            notes: 'Height should be 1.2–2.5 times the width for optimal display',
            supportsFlexible: false
        },
        {
            id: 'pinterest-square',
            displayName: 'Pinterest Square Pin',
            width: '1000px',
            height: '1000px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['pinterest'],
            commonUses: ['pin', 'infographic'],
            requiresCrop: true,
            minWidth: 1000,
            minHeight: 1000,
            description: 'Pinterest square pin',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '10MB',
            notes: 'Good for infographics and step-by-step guides',
            supportsFlexible: false
        },
        {
            id: 'pinterest-story',
            displayName: 'Pinterest Story Pin',
            width: '1080px',
            height: '1920px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['pinterest'],
            commonUses: ['story', 'vertical-content'],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1920,
            description: 'Pinterest Story pin (full-screen vertical)',
            aspectRatio: '9:16',
            maxSize: '10MB',
            notes: 'Similar format to Instagram/Facebook Stories',
            supportsFlexible: false
        },

        // TikTok
        {
            id: 'tiktok-profile',
            displayName: 'TikTok Profile Picture',
            width: '200px',
            height: '200px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['tiktok'],
            commonUses: ['profile', 'avatar'],
            requiresCrop: true,
            minWidth: 200,
            minHeight: 200,
            description: 'TikTok profile picture',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '5MB',
            notes: 'Upload at 200×200, minimum 20×20',
            supportsFlexible: false
        },
        {
            id: 'tiktok-video',
            displayName: 'TikTok Video Cover',
            width: '1080px',
            height: '1920px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['tiktok'],
            commonUses: ['video-cover', 'thumbnail'],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1920,
            description: 'TikTok video cover/thumbnail',
            aspectRatio: '9:16',
            maxSize: '5MB',
            notes: 'Full-screen vertical format, same as video dimensions',
            supportsFlexible: false
        },

        // === WEB TEMPLATES ===
        {
            id: 'web-hero',
            displayName: 'Hero Banner',
            width: '1920px',
            height: '1080px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG],
            platforms: ['web', 'desktop', 'responsive'],
            commonUses: ['website-hero', 'landing-page'],
            requiresCrop: false,
            minWidth: 1920,
            minHeight: 1080,
            description: 'Full-width hero banner for websites',
            aspectRatio: AspectRatios.SIXTEEN_NINE,
            maxSize: '200KB',
            notes: 'Optimize for fast loading, consider responsive breakpoints',
            supportsFlexible: false
        },
        {
            id: 'web-blog',
            displayName: 'Blog Featured Image',
            width: '1200px',
            height: '630px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG],
            platforms: ['web', 'blog', 'social'],
            commonUses: ['blog-post', 'article'],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 630,
            description: 'Blog post featured image (Open Graph optimal)',
            aspectRatio: '1.91:1',
            maxSize: '100KB',
            notes: 'Also works for social media sharing previews',
            supportsFlexible: false
        },
        {
            id: 'web-content',
            displayName: 'Content Image',
            width: '1200px',
            height: 'variable',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['web', 'article', 'content'],
            commonUses: ['article-content', 'page-content'],
            requiresCrop: false,
            minWidth: 1200,
            minHeight: 600,
            description: 'General content images within articles/pages',
            aspectRatio: 'flexible',
            maxSize: '150KB',
            supportsFlexible: true,
            notes: 'Flexible height that maintains natural aspect ratio'
        },
        {
            id: 'web-thumb',
            displayName: 'Thumbnail',
            width: '300px',
            height: '300px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG],
            platforms: ['web', 'gallery', 'ecommerce'],
            commonUses: ['gallery-thumbnail', 'product-thumbnail'],
            requiresCrop: true,
            minWidth: 300,
            minHeight: 300,
            description: 'Small thumbnails for galleries, products, listings',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '30KB',
            notes: 'Keep file size small for grid views',
            supportsFlexible: false
        },
        {
            id: 'web-card',
            displayName: 'Card Image',
            width: '400px',
            height: '300px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG],
            platforms: ['web', 'ui', 'cards'],
            commonUses: ['feature-card', 'product-card', 'ui-component'],
            requiresCrop: true,
            minWidth: 400,
            minHeight: 300,
            description: 'Images for feature cards, product cards, etc.',
            aspectRatio: AspectRatios.FOUR_THREE,
            maxSize: '50KB',
            notes: 'Common card aspect ratio',
            supportsFlexible: false
        },
        {
            id: 'web-og',
            displayName: 'Open Graph Image',
            width: '1200px',
            height: '630px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['web', 'social'],
            commonUses: ['social-sharing', 'link-preview'],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 630,
            description: 'Social sharing preview image',
            aspectRatio: '1.91:1',
            maxSize: '100KB',
            notes: 'Essential for social media link sharing',
            supportsFlexible: false
        },

        // === EXISTING TEMPLATES FROM ORIGINAL templateConfig.js ===
        {
            id: 'web-banner-leaderboard',
            displayName: 'Web Banner (Leaderboard)',
            description: 'Standard leaderboard banner for websites',
            width: '728px',
            height: '90px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.PNG, FileExtensions.JPEG],
            platforms: ['web', 'desktop'],
            commonUses: ['advertising', 'header'],
            requiresCrop: false,
            minWidth: 728,
            minHeight: 90,
            supportsFlexible: false
        },
        {
            id: 'web-banner-skyscraper',
            displayName: 'Web Banner (Skyscraper)',
            description: 'Vertical skyscraper banner',
            width: '160px',
            height: '600px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.PNG, FileExtensions.JPEG],
            platforms: ['web', 'desktop'],
            commonUses: ['advertising', 'sidebar'],
            requiresCrop: false,
            minWidth: 160,
            minHeight: 600,
            supportsFlexible: false
        },
        {
            id: 'web-banner-medium',
            displayName: 'Web Banner (Medium Rectangle)',
            description: 'Medium rectangle banner',
            width: '300px',
            height: '250px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.PNG, FileExtensions.JPEG],
            platforms: ['web', 'desktop'],
            commonUses: ['advertising', 'content'],
            requiresCrop: false,
            minWidth: 300,
            minHeight: 250,
            supportsFlexible: false
        },
        {
            id: 'responsive-hero',
            displayName: 'Responsive Hero Image',
            description: 'Full-width hero image for responsive designs',
            width: '1920px',
            height: '1080px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.AVIF, FileExtensions.JPEG],
            platforms: ['web', 'mobile', 'tablet'],
            commonUses: ['website-hero', 'landing-page'],
            requiresCrop: false,
            minWidth: 1200,
            minHeight: 600,
            supportsFlexible: false
        },
        {
            id: 'social-facebook-post',
            displayName: 'Facebook Post',
            description: 'Image for Facebook feed posts',
            width: '1200px',
            height: '630px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['facebook'],
            commonUses: ['social-media', 'sharing'],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 630,
            supportsFlexible: false
        },
        {
            id: 'social-facebook-cover',
            displayName: 'Facebook Cover Photo',
            description: 'Cover photo for Facebook pages',
            width: '820px',
            height: '312px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['facebook'],
            commonUses: ['social-media', 'profile'],
            requiresCrop: true,
            minWidth: 820,
            minHeight: 312,
            supportsFlexible: false
        },
        {
            id: 'social-instagram-square',
            displayName: 'Instagram Square Post',
            description: 'Square image for Instagram feed',
            width: '1080px',
            height: '1080px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG],
            platforms: ['instagram'],
            commonUses: ['social-media', 'feed'],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1080,
            supportsFlexible: false
        },
        {
            id: 'social-instagram-portrait',
            displayName: 'Instagram Portrait',
            description: 'Portrait image for Instagram',
            width: '1080px',
            height: '1350px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG],
            platforms: ['instagram'],
            commonUses: ['social-media', 'stories'],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1350,
            supportsFlexible: false
        },
        {
            id: 'social-twitter-post',
            displayName: 'Twitter Post',
            description: 'Image for Twitter posts',
            width: '1200px',
            height: '675px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['twitter'],
            commonUses: ['social-media', 'tweet'],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 675,
            supportsFlexible: false
        },
        {
            id: 'social-linkedin-post',
            displayName: 'LinkedIn Post',
            description: 'Image for LinkedIn posts',
            width: '1200px',
            height: '627px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['linkedin'],
            commonUses: ['professional', 'networking'],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 627,
            supportsFlexible: false
        },
        {
            id: 'logo-favicon',
            displayName: 'Favicon',
            description: 'Small icon for browser tabs',
            width: '16px',
            height: '16px',
            category: TemplateCategories.LOGO,
            recommendedFormats: [FileExtensions.ICO, FileExtensions.PNG, FileExtensions.SVG],
            platforms: ['web', 'browser'],
            commonUses: ['website-icon', 'browser-tab'],
            requiresCrop: true,
            minWidth: 16,
            minHeight: 16,
            supportsFlexible: false
        },
        {
            id: 'logo-app-icon',
            displayName: 'App Icon',
            description: 'Icon for mobile applications',
            width: '1024px',
            height: '1024px',
            category: TemplateCategories.LOGO,
            recommendedFormats: [FileExtensions.PNG],
            platforms: ['ios', 'android'],
            commonUses: ['mobile-app', 'store'],
            requiresCrop: true,
            minWidth: 1024,
            minHeight: 1024,
            supportsFlexible: false
        },
        {
            id: 'logo-social-profile',
            displayName: 'Social Profile Picture',
            description: 'Profile picture for social media',
            width: '400px',
            height: '400px',
            category: TemplateCategories.LOGO,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: ['facebook', 'twitter', 'instagram', 'linkedin'],
            commonUses: ['profile', 'avatar'],
            requiresCrop: true,
            minWidth: 400,
            minHeight: 400,
            supportsFlexible: false
        },
        {
            id: 'ecommerce-product',
            displayName: 'Product Image',
            description: 'Main product image for e-commerce',
            width: '800px',
            height: '800px',
            category: TemplateCategories.ECOMMERCE,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG],
            platforms: ['shopify', 'woocommerce', 'amazon'],
            commonUses: ['product', 'catalog'],
            requiresCrop: true,
            minWidth: 800,
            minHeight: 800,
            supportsFlexible: false
        },
        {
            id: 'ecommerce-gallery',
            displayName: 'Product Gallery Image',
            description: 'Additional images for product gallery',
            width: '1000px',
            height: '1000px',
            category: TemplateCategories.ECOMMERCE,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG],
            platforms: ['shopify', 'woocommerce'],
            commonUses: ['gallery', 'product-detail'],
            requiresCrop: true,
            minWidth: 1000,
            minHeight: 1000,
            supportsFlexible: false
        },
        {
            id: 'print-business-card',
            displayName: 'Business Card',
            description: 'Standard business card design',
            width: '3.5in',
            height: '2in',
            category: TemplateCategories.PRINT,
            recommendedFormats: [FileExtensions.PDF, FileExtensions.PNG, FileExtensions.JPEG],
            platforms: ['print'],
            commonUses: ['business', 'networking'],
            requiresCrop: true,
            minWidth: 1050,
            minHeight: 600,
            supportsFlexible: false
        },
        {
            id: 'print-flyer',
            displayName: 'Flyer',
            description: 'Standard flyer size',
            width: '8.5in',
            height: '11in',
            category: TemplateCategories.PRINT,
            recommendedFormats: [FileExtensions.PDF, FileExtensions.PNG, FileExtensions.JPEG],
            platforms: ['print'],
            commonUses: ['marketing', 'promotion'],
            requiresCrop: true,
            minWidth: 2550,
            minHeight: 3300,
            supportsFlexible: false
        },
        {
            id: 'flexible-web-image',
            displayName: 'Flexible Web Image',
            description: 'Web image with flexible width',
            width: 'variable',
            height: '600px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG],
            platforms: ['web', 'responsive'],
            commonUses: ['content', 'article'],
            requiresCrop: false,
            minWidth: 300,
            minHeight: 600,
            supportsFlexible: true
        },
        {
            id: 'flexible-mobile-hero',
            displayName: 'Flexible Mobile Hero',
            description: 'Hero image for mobile devices',
            width: 'variable',
            height: 'variable',
            category: TemplateCategories.MOBILE,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.AVIF],
            platforms: ['mobile', 'responsive'],
            commonUses: ['mobile-app', 'responsive-web'],
            requiresCrop: false,
            minWidth: 320,
            minHeight: 568,
            supportsFlexible: true
        },
        {
            id: 'favicon-set',
            displayName: 'Favicon Set',
            description: 'Multiple favicon sizes for modern browsers',
            width: 'variable',
            height: 'variable',
            category: TemplateCategories.FAVICON,
            recommendedFormats: [FileExtensions.PNG, FileExtensions.ICO, FileExtensions.SVG],
            platforms: ['web', 'browser'],
            commonUses: ['website-icon', 'pwa'],
            requiresCrop: true,
            minWidth: 16,
            minHeight: 16,
            sizes: [16, 32, 48, 64, 128, 256],
            supportsFlexible: true
        }
    ],

    // Categorized templates for easy access
    [TemplateCategories.WEB]: [],
    [TemplateCategories.SOCIAL]: [],
    [TemplateCategories.LOGO]: [],
    [TemplateCategories.ECOMMERCE]: [],
    [TemplateCategories.PRINT]: [],
    [TemplateCategories.FLEXIBLE]: [],
    [TemplateCategories.FAVICON]: [],
    [TemplateCategories.MOBILE]: [],
    [TemplateCategories.GENERAL]: []
};

// Initialize categorized arrays
LemGendTemplates.ALL.forEach(template => {
    const category = template.category;
    if (category && TemplateCategoryKeys.includes(category) && LemGendTemplates[category]) {
        LemGendTemplates[category].push(template);
    }

    // Ensure all templates have the supportsFlexible property
    if (template.supportsFlexible === undefined) {
        const widthInfo = template.width?.toString().toLowerCase();
        const heightInfo = template.height?.toString().toLowerCase();
        template.supportsFlexible = widthInfo === 'variable' || heightInfo === 'variable' ||
            widthInfo === 'flexible' || heightInfo === 'flexible' ||
            category === TemplateCategories.FLEXIBLE;
    }
});