// templates/templateConfig.js - COMPLETE Template Database

// Import constants
import {
    TemplateCategories,
    TemplateCategoryKeys,
    FileExtensions,
    AspectRatios,
    PlatformTypes,
    CommonUses
} from '../constants/sharedConstants.js';

// ===== COMPLETE TEMPLATE DATABASE =====
export const LemGendTemplates = {
    ALL: [
        // === FAVICON TEMPLATES ===
        {
            id: 'favicon-basic',
            displayName: 'Basic Favicon',
            width: '16px',
            height: '16px',
            category: TemplateCategories.FAVICON,
            recommendedFormats: [FileExtensions.ICO, FileExtensions.PNG],
            platforms: [PlatformTypes.WEB, PlatformTypes.BROWSER],
            commonUses: [CommonUses.WEBSITE_ICON, CommonUses.BROWSER_TAB],
            requiresCrop: true,
            minWidth: 16,
            minHeight: 16,
            description: 'Standard 16×16 favicon for browser tabs',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '1KB',
            notes: 'Required for most browsers, displays in browser tabs',
            supportsFlexible: false
        },
        {
            id: 'favicon-apple',
            displayName: 'Apple Touch Icon',
            width: '180px',
            height: '180px',
            category: TemplateCategories.FAVICON,
            recommendedFormats: [FileExtensions.PNG],
            platforms: [PlatformTypes.IOS, PlatformTypes.MOBILE],
            commonUses: [CommonUses.MOBILE_APP, CommonUses.HOME_SCREEN],
            requiresCrop: true,
            minWidth: 180,
            minHeight: 180,
            description: 'Apple devices home screen icon',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '20KB',
            notes: 'For iOS devices when saving to home screen',
            supportsFlexible: false
        },
        {
            id: 'favicon-android',
            displayName: 'Android Chrome Icon',
            width: '192px',
            height: '192px',
            category: TemplateCategories.FAVICON,
            recommendedFormats: [FileExtensions.PNG],
            platforms: [PlatformTypes.ANDROID, PlatformTypes.MOBILE],
            commonUses: [CommonUses.MOBILE_APP, CommonUses.HOME_SCREEN],
            requiresCrop: true,
            minWidth: 192,
            minHeight: 192,
            description: 'Android Chrome home screen icon',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '20KB',
            notes: 'For Android devices when saving to home screen',
            supportsFlexible: false
        },
        {
            id: 'favicon-safari',
            displayName: 'Safari Pinned Tab',
            width: '16px',
            height: '16px',
            category: TemplateCategories.FAVICON,
            recommendedFormats: [FileExtensions.SVG],
            platforms: [PlatformTypes.SAFARI, PlatformTypes.BROWSER],
            commonUses: [CommonUses.WEBSITE_ICON, CommonUses.PINNED_TAB],
            requiresCrop: true,
            minWidth: 16,
            minHeight: 16,
            description: 'SVG icon for Safari pinned tabs',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '5KB',
            notes: 'Monochrome SVG for Safari pinned tabs feature',
            supportsFlexible: false
        },
        {
            id: 'favicon-windows',
            displayName: 'Windows Tile',
            width: '144px',
            height: '144px',
            category: TemplateCategories.FAVICON,
            recommendedFormats: [FileExtensions.PNG],
            platforms: [PlatformTypes.WINDOWS, PlatformTypes.DESKTOP],
            commonUses: [CommonUses.WINDOWS_APP, CommonUses.START_MENU],
            requiresCrop: true,
            minWidth: 144,
            minHeight: 144,
            description: 'Windows 8/10 start menu tile icon',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '15KB',
            notes: 'For Windows devices when pinning to start menu',
            supportsFlexible: false
        },
        {
            id: 'favicon-retina',
            displayName: 'Retina Favicon',
            width: '64px',
            height: '64px',
            category: TemplateCategories.FAVICON,
            recommendedFormats: [FileExtensions.PNG, FileExtensions.ICO],
            platforms: [PlatformTypes.WEB, PlatformTypes.BROWSER, PlatformTypes.RETINA],
            commonUses: [CommonUses.WEBSITE_ICON, CommonUses.HIGH_DPI],
            requiresCrop: true,
            minWidth: 64,
            minHeight: 64,
            description: 'High-resolution favicon for retina displays',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '15KB',
            notes: 'For high-DPI screens, includes @2x and @3x versions',
            supportsFlexible: false
        },
        {
            id: 'favicon-standard',
            displayName: 'Standard Favicon Set',
            width: '32px',
            height: '32px',
            category: TemplateCategories.FAVICON,
            recommendedFormats: [FileExtensions.ICO],
            platforms: [PlatformTypes.WEB, PlatformTypes.BROWSER],
            commonUses: [CommonUses.WEBSITE_ICON, CommonUses.BROWSER_TAB],
            requiresCrop: true,
            minWidth: 32,
            minHeight: 32,
            description: 'Standard favicon set for desktop browsers',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '10KB',
            notes: 'Includes 16×16, 32×32, 48×48 sizes in single .ico file',
            supportsFlexible: false
        },
        {
            id: 'favicon-modern',
            displayName: 'Modern Favicon Set',
            width: '180px',
            height: '180px',
            category: TemplateCategories.FAVICON,
            recommendedFormats: [FileExtensions.PNG, FileExtensions.SVG],
            platforms: [PlatformTypes.WEB, PlatformTypes.BROWSER, PlatformTypes.MOBILE],
            commonUses: [CommonUses.WEBSITE_ICON, CommonUses.PWA, CommonUses.MOBILE],
            requiresCrop: true,
            minWidth: 180,
            minHeight: 180,
            description: 'Complete favicon set for all modern devices',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '30KB',
            notes: 'Includes iOS home screen, Android, Safari pinned tab, Windows tile',
            supportsFlexible: false
        },
        {
            id: 'favicon-complete',
            displayName: 'Complete Favicon Package',
            width: '512px',
            height: '512px',
            category: TemplateCategories.FAVICON,
            recommendedFormats: [FileExtensions.ICO, FileExtensions.PNG, FileExtensions.SVG],
            platforms: [PlatformTypes.WEB, PlatformTypes.BROWSER, PlatformTypes.MOBILE, PlatformTypes.DESKTOP],
            commonUses: [CommonUses.WEBSITE_ICON, CommonUses.COMPLETE_PACKAGE],
            requiresCrop: true,
            minWidth: 512,
            minHeight: 512,
            description: 'Complete favicon package with all necessary sizes',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '50KB',
            notes: 'Includes all sizes: 16×16, 32×32, 48×48, 64×64, 128×128, 180×180, 192×192, 256×256, 512×512',
            supportsFlexible: true
        },
        // === LOGO TEMPLATES ===
        {
            id: 'logo-rectangular',
            displayName: 'Rectangular Logo',
            width: '300px',
            height: '150px',
            category: TemplateCategories.LOGO,
            recommendedFormats: [FileExtensions.PNG, FileExtensions.SVG],
            platforms: [PlatformTypes.WEB, PlatformTypes.PRINT, PlatformTypes.EMAIL],
            commonUses: [CommonUses.WEBSITE_HEADER, CommonUses.EMAIL_SIGNATURE, CommonUses.DOCUMENTATION],
            requiresCrop: true,
            minWidth: 300,
            minHeight: 150,
            description: 'Standard rectangular logo format',
            aspectRatio: AspectRatios.TWO_ONE,
            maxSize: '50KB',
            notes: 'Good for website headers and email signatures',
            supportsFlexible: false
        },
        {
            id: 'logo-square',
            displayName: 'Square Logo',
            width: '500px',
            height: '500px',
            category: TemplateCategories.LOGO,
            recommendedFormats: [FileExtensions.PNG, FileExtensions.SVG],
            platforms: [PlatformTypes.SOCIAL, PlatformTypes.WEB, PlatformTypes.MOBILE],
            commonUses: [CommonUses.SOCIAL_MEDIA, CommonUses.MOBILE_APP, CommonUses.PROFILE],
            requiresCrop: true,
            minWidth: 500,
            minHeight: 500,
            description: 'Square logo for social media and apps',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '50KB',
            notes: 'Required for many social media platforms',
            supportsFlexible: false
        },
        {
            id: 'logo-print',
            displayName: 'Print-Ready Logo',
            width: '3000px',
            height: '3000px',
            category: TemplateCategories.LOGO,
            recommendedFormats: [FileExtensions.PNG, FileExtensions.SVG, FileExtensions.PDF, FileExtensions.EPS],
            platforms: [PlatformTypes.PRINT],
            commonUses: [CommonUses.BUSINESS_CARD, CommonUses.BROCHURE, CommonUses.SIGNAGE],
            requiresCrop: true,
            minWidth: 3000,
            minHeight: 3000,
            description: 'High-resolution logo for print materials',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '2MB',
            notes: '300 DPI minimum for quality printing',
            supportsFlexible: false
        },
        {
            id: 'logo-watermark',
            displayName: 'Watermark',
            width: '1000px',
            height: '400px',
            category: TemplateCategories.LOGO,
            recommendedFormats: [FileExtensions.PNG],
            platforms: [PlatformTypes.PHOTO, PlatformTypes.VIDEO],
            commonUses: [CommonUses.PHOTO_PROTECTION, CommonUses.BRANDING, CommonUses.VIDEO_OVERLAY],
            requiresCrop: true,
            minWidth: 1000,
            minHeight: 400,
            description: 'Semi-transparent watermark for photos',
            aspectRatio: AspectRatios.FIVE_TWO,
            maxSize: '50KB',
            notes: 'Use PNG with transparency for overlay',
            supportsFlexible: false
        },
        {
            id: 'logo-vertical',
            displayName: 'Vertical Logo',
            width: '500px',
            height: '800px',
            category: TemplateCategories.LOGO,
            recommendedFormats: [FileExtensions.PNG, FileExtensions.SVG],
            platforms: [PlatformTypes.MOBILE, PlatformTypes.DOCUMENTATION],
            commonUses: [CommonUses.MOBILE_APP, CommonUses.DOCUMENT_HEADER, CommonUses.PRESENTATION],
            requiresCrop: true,
            minWidth: 500,
            minHeight: 800,
            description: 'Tall logo for vertical spaces',
            aspectRatio: AspectRatios.TWO_THREE,
            maxSize: '50KB',
            notes: 'Good for mobile apps and documentation',
            supportsFlexible: false
        },
        {
            id: 'logo-app-icon',
            displayName: 'App Icon',
            width: '1024px',
            height: '1024px',
            category: TemplateCategories.LOGO,
            recommendedFormats: [FileExtensions.PNG],
            platforms: [PlatformTypes.IOS, PlatformTypes.ANDROID],
            commonUses: [CommonUses.MOBILE_APP, CommonUses.STORE],
            requiresCrop: true,
            minWidth: 1024,
            minHeight: 1024,
            description: 'Icon for mobile applications',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '2MB',
            notes: 'Required for app store submissions',
            supportsFlexible: false
        },
        {
            id: 'logo-social-profile',
            displayName: 'Social Profile Picture',
            width: '400px',
            height: '400px',
            category: TemplateCategories.LOGO,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.FACEBOOK, PlatformTypes.TWITTER, PlatformTypes.INSTAGRAM, PlatformTypes.LINKEDIN],
            commonUses: [CommonUses.PROFILE, CommonUses.AVATAR],
            requiresCrop: true,
            minWidth: 400,
            minHeight: 400,
            description: 'Profile picture for social media',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '2MB',
            notes: 'Optimized for social media profile pictures',
            supportsFlexible: false
        },
        // === SOCIAL MEDIA TEMPLATES ===
        // Facebook
        {
            id: 'facebook-profile',
            displayName: 'Facebook Profile Picture',
            width: '180px',
            height: '180px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.FACEBOOK],
            commonUses: [CommonUses.PROFILE, CommonUses.AVATAR],
            requiresCrop: true,
            minWidth: 180,
            minHeight: 180,
            description: 'Facebook profile picture (displays as 170×170 on desktop)',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '5MB',
            notes: 'Minimum 180×180, displays as circular',
            supportsFlexible: false
        },
        {
            id: 'facebook-cover',
            displayName: 'Facebook Cover Photo',
            width: '851px',
            height: '315px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.FACEBOOK],
            commonUses: [CommonUses.COVER, CommonUses.BANNER],
            requiresCrop: true,
            minWidth: 851,
            minHeight: 315,
            description: 'Facebook page and profile cover photo',
            aspectRatio: AspectRatios.TWENTYSEVEN_TEN,
            maxSize: '100KB',
            notes: 'Displays as 820×312 on desktop, mobile crops sides',
            supportsFlexible: false
        },
        {
            id: 'facebook-shared',
            displayName: 'Facebook Shared Image',
            width: '1200px',
            height: '630px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.FACEBOOK],
            commonUses: [CommonUses.SHARED_POST, CommonUses.LINK_PREVIEW],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 630,
            description: 'Optimal size for shared links and images in feed',
            aspectRatio: AspectRatios.NINETEEN_TEN,
            maxSize: '8MB',
            notes: 'Ideal for link previews and engagement',
            supportsFlexible: false
        },
        {
            id: 'facebook-square',
            displayName: 'Facebook Square Post',
            width: '1200px',
            height: '1200px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.FACEBOOK],
            commonUses: [CommonUses.FEED_POST, CommonUses.ALBUM],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 1200,
            description: 'Facebook square post images',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '8MB',
            notes: 'Good for product shots and albums',
            supportsFlexible: false
        },
        {
            id: 'facebook-stories',
            displayName: 'Facebook Stories',
            width: '1080px',
            height: '1920px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.FACEBOOK],
            commonUses: [CommonUses.STORIES],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1920,
            description: 'Facebook Stories (full-screen vertical)',
            aspectRatio: AspectRatios.NINE_SIXTEEN,
            maxSize: '4MB',
            notes: 'Same as Instagram Stories format',
            supportsFlexible: false
        },
        {
            id: 'social-facebook-post',
            displayName: 'Facebook Post',
            width: '1200px',
            height: '630px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.FACEBOOK],
            commonUses: [CommonUses.SOCIAL_MEDIA, CommonUses.SHARING],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 630,
            description: 'Image for Facebook feed posts',
            aspectRatio: AspectRatios.NINETEEN_TEN,
            maxSize: '8MB',
            notes: 'Optimal size for Facebook feed',
            supportsFlexible: false
        },
        {
            id: 'social-facebook-cover',
            displayName: 'Facebook Cover Photo',
            width: '820px',
            height: '312px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.FACEBOOK],
            commonUses: [CommonUses.SOCIAL_MEDIA, CommonUses.PROFILE],
            requiresCrop: true,
            minWidth: 820,
            minHeight: 312,
            description: 'Cover photo for Facebook pages',
            aspectRatio: AspectRatios.TWENTYSEVEN_TEN,
            maxSize: '100KB',
            notes: 'Optimized for Facebook cover display',
            supportsFlexible: false
        },
        // Instagram
        {
            id: 'instagram-profile',
            displayName: 'Instagram Profile Picture',
            width: '320px',
            height: '320px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.WEBP],
            platforms: [PlatformTypes.INSTAGRAM],
            commonUses: [CommonUses.PROFILE, CommonUses.AVATAR],
            requiresCrop: true,
            minWidth: 320,
            minHeight: 320,
            description: 'Instagram profile picture (displays as circular 110×110 in app)',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '100KB',
            notes: 'Upload at 320×320 for best quality, will be cropped to circle',
            supportsFlexible: false
        },
        {
            id: 'instagram-square',
            displayName: 'Instagram Square Post',
            width: '1080px',
            height: '1080px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.WEBP],
            platforms: [PlatformTypes.INSTAGRAM],
            commonUses: [CommonUses.SOCIAL_MEDIA, CommonUses.FEED_POST],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1080,
            description: 'Instagram square photo/video posts',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '8MB',
            notes: 'Optimal for grid view, displays at 600×600',
            supportsFlexible: false
        },
        {
            id: 'instagram-portrait',
            displayName: 'Instagram Portrait Post',
            width: '1080px',
            height: '1350px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.WEBP],
            platforms: [PlatformTypes.INSTAGRAM],
            commonUses: [CommonUses.SOCIAL_MEDIA, CommonUses.FEED_POST],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1350,
            description: 'Instagram portrait (vertical) posts',
            aspectRatio: AspectRatios.THREE_FOUR,
            maxSize: '8MB',
            notes: 'Takes more space in feed, good for full-body shots',
            supportsFlexible: false
        },
        {
            id: 'instagram-landscape',
            displayName: 'Instagram Landscape Post',
            width: '1080px',
            height: '566px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.WEBP],
            platforms: [PlatformTypes.INSTAGRAM],
            commonUses: [CommonUses.SOCIAL_MEDIA, CommonUses.FEED_POST],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 566,
            description: 'Instagram landscape (horizontal) posts',
            aspectRatio: AspectRatios.NINETEEN_TEN,
            maxSize: '8MB',
            notes: 'Good for group photos and scenery',
            supportsFlexible: false
        },
        {
            id: 'instagram-stories',
            displayName: 'Instagram Stories & Reels',
            width: '1080px',
            height: '1920px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.WEBP],
            platforms: [PlatformTypes.INSTAGRAM],
            commonUses: [CommonUses.STORIES, CommonUses.REELS, CommonUses.IGTV],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1920,
            description: 'Instagram Stories, Reels, and IGTV covers',
            aspectRatio: AspectRatios.NINE_SIXTEEN,
            maxSize: '4MB',
            notes: 'Full-screen vertical format, safe area: center 1080×1420',
            supportsFlexible: false
        },
        {
            id: 'social-instagram-square',
            displayName: 'Instagram Square Post',
            width: '1080px',
            height: '1080px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG],
            platforms: [PlatformTypes.INSTAGRAM],
            commonUses: [CommonUses.SOCIAL_MEDIA, CommonUses.FEED],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1080,
            description: 'Square image for Instagram feed',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '8MB',
            notes: 'Standard square format for Instagram',
            supportsFlexible: false
        },
        {
            id: 'social-instagram-portrait',
            displayName: 'Instagram Portrait',
            width: '1080px',
            height: '1350px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG],
            platforms: [PlatformTypes.INSTAGRAM],
            commonUses: [CommonUses.SOCIAL_MEDIA, CommonUses.STORIES],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1350,
            description: 'Portrait image for Instagram',
            aspectRatio: AspectRatios.THREE_FOUR,
            maxSize: '8MB',
            notes: 'Portrait format for Instagram',
            supportsFlexible: false
        },
        // Twitter/X
        {
            id: 'twitter-profile',
            displayName: 'Twitter/X Profile Picture',
            width: '400px',
            height: '400px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.TWITTER],
            commonUses: [CommonUses.PROFILE, CommonUses.AVATAR],
            requiresCrop: true,
            minWidth: 400,
            minHeight: 400,
            description: 'Twitter/X profile picture (displays as 200×200)',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '2MB',
            notes: 'Upload at 400×400, displays as circular',
            supportsFlexible: false
        },
        {
            id: 'twitter-header',
            displayName: 'Twitter/X Header Banner',
            width: '1500px',
            height: '500px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.TWITTER],
            commonUses: [CommonUses.HEADER, CommonUses.BANNER],
            requiresCrop: true,
            minWidth: 1500,
            minHeight: 500,
            description: 'Twitter/X header banner',
            aspectRatio: AspectRatios.THREE_ONE,
            maxSize: '5MB',
            notes: 'Minimum 1500×500, important content in center',
            supportsFlexible: false
        },
        {
            id: 'twitter-landscape',
            displayName: 'Twitter/X Landscape Post',
            width: '1600px',
            height: '900px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.TWITTER],
            commonUses: [CommonUses.TWEET, CommonUses.SCREENSHOT],
            requiresCrop: true,
            minWidth: 1600,
            minHeight: 900,
            description: 'Twitter/X landscape image in tweet',
            aspectRatio: AspectRatios.SIXTEEN_NINE,
            maxSize: '5MB',
            notes: 'Optimal for screenshots and wide images',
            supportsFlexible: false
        },
        {
            id: 'twitter-square',
            displayName: 'Twitter/X Square Post',
            width: '1080px',
            height: '1080px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.TWITTER],
            commonUses: [CommonUses.TWEET, CommonUses.PRODUCT_IMAGE],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1080,
            description: 'Twitter/X square image in tweet',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '5MB',
            notes: 'Good for product images and infographics',
            supportsFlexible: false
        },
        {
            id: 'twitter-portrait',
            displayName: 'Twitter/X Portrait Post',
            width: '1080px',
            height: '1350px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.TWITTER],
            commonUses: [CommonUses.TWEET, CommonUses.PORTRAIT_IMAGE],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1350,
            description: 'Twitter/X portrait (vertical) image',
            aspectRatio: AspectRatios.THREE_FOUR,
            maxSize: '5MB',
            notes: 'Similar to Instagram portrait format',
            supportsFlexible: false
        },
        {
            id: 'social-twitter-post',
            displayName: 'Twitter Post',
            width: '1200px',
            height: '675px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.TWITTER],
            commonUses: [CommonUses.SOCIAL_MEDIA, CommonUses.TWEET],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 675,
            description: 'Image for Twitter posts',
            aspectRatio: AspectRatios.SIXTEEN_NINE,
            maxSize: '5MB',
            notes: 'Optimal size for Twitter posts',
            supportsFlexible: false
        },
        // LinkedIn
        {
            id: 'linkedin-profile',
            displayName: 'LinkedIn Profile Picture',
            width: '400px',
            height: '400px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.LINKEDIN],
            commonUses: [CommonUses.PROFILE, CommonUses.AVATAR],
            requiresCrop: true,
            minWidth: 400,
            minHeight: 400,
            description: 'LinkedIn profile picture (displays as circular)',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '8MB',
            notes: 'Upload at 400×400, minimum 300×300',
            supportsFlexible: false
        },
        {
            id: 'linkedin-cover',
            displayName: 'LinkedIn Personal Cover Photo',
            width: '1584px',
            height: '396px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.LINKEDIN],
            commonUses: [CommonUses.COVER, CommonUses.BANNER],
            requiresCrop: true,
            minWidth: 1584,
            minHeight: 396,
            description: 'LinkedIn personal profile cover photo',
            aspectRatio: AspectRatios.FOUR_ONE,
            maxSize: '8MB',
            notes: 'Displays as 1400×425, keep important content centered',
            supportsFlexible: false
        },
        {
            id: 'linkedin-landscape',
            displayName: 'LinkedIn Landscape Post',
            width: '1200px',
            height: '627px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.LINKEDIN],
            commonUses: [CommonUses.POST, CommonUses.ARTICLE],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 627,
            description: 'LinkedIn landscape post images',
            aspectRatio: AspectRatios.NINETEEN_TEN,
            maxSize: '5MB',
            notes: 'Optimal for shared links and articles',
            supportsFlexible: false
        },
        {
            id: 'linkedin-square',
            displayName: 'LinkedIn Square Post',
            width: '1200px',
            height: '1200px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.LINKEDIN],
            commonUses: [CommonUses.POST, CommonUses.INFOGRAPHIC],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 1200,
            description: 'LinkedIn square post images',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '5MB',
            notes: 'Good for infographics and product images',
            supportsFlexible: false
        },
        {
            id: 'linkedin-portrait',
            displayName: 'LinkedIn Portrait Post',
            width: '720px',
            height: '900px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.LINKEDIN],
            commonUses: [CommonUses.POST, CommonUses.VERTICAL_IMAGE],
            requiresCrop: true,
            minWidth: 720,
            minHeight: 900,
            description: 'LinkedIn portrait (vertical) post images',
            aspectRatio: AspectRatios.THREE_FOUR,
            maxSize: '5MB',
            notes: 'Less common but supported format',
            supportsFlexible: false
        },
        {
            id: 'social-linkedin-post',
            displayName: 'LinkedIn Post',
            width: '1200px',
            height: '627px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.LINKEDIN],
            commonUses: [CommonUses.PROFESSIONAL, CommonUses.NETWORKING],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 627,
            description: 'Image for LinkedIn posts',
            aspectRatio: AspectRatios.NINETEEN_TEN,
            maxSize: '5MB',
            notes: 'Optimal size for LinkedIn posts',
            supportsFlexible: false
        },
        // YouTube
        {
            id: 'youtube-channel',
            displayName: 'YouTube Channel Icon',
            width: '800px',
            height: '800px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.YOUTUBE],
            commonUses: [CommonUses.PROFILE, CommonUses.CHANNEL_ICON],
            requiresCrop: true,
            minWidth: 800,
            minHeight: 800,
            description: 'YouTube channel profile picture',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '2MB',
            notes: 'Displays as 98×98 in most places',
            supportsFlexible: false
        },
        {
            id: 'youtube-banner',
            displayName: 'YouTube Channel Banner',
            width: '2048px',
            height: '1152px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.YOUTUBE],
            commonUses: [CommonUses.BANNER, CommonUses.CHANNEL_ART],
            requiresCrop: true,
            minWidth: 2048,
            minHeight: 1152,
            description: 'YouTube channel banner/header',
            aspectRatio: AspectRatios.SIXTEEN_NINE,
            maxSize: '6MB',
            notes: 'Safe area for mobile: 1546×423, important content centered',
            supportsFlexible: false
        },
        {
            id: 'youtube-thumbnail',
            displayName: 'YouTube Video Thumbnail',
            width: '1280px',
            height: '720px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.YOUTUBE],
            commonUses: [CommonUses.THUMBNAIL, CommonUses.VIDEO_PREVIEW],
            requiresCrop: true,
            minWidth: 1280,
            minHeight: 720,
            description: 'YouTube video thumbnail',
            aspectRatio: AspectRatios.SIXTEEN_NINE,
            maxSize: '2MB',
            notes: 'Minimum 640×480, 16:9 recommended for all devices',
            supportsFlexible: false
        },
        // Pinterest
        {
            id: 'pinterest-profile',
            displayName: 'Pinterest Profile Picture',
            width: '165px',
            height: '165px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.PINTEREST],
            commonUses: [CommonUses.PROFILE, CommonUses.AVATAR],
            requiresCrop: true,
            minWidth: 165,
            minHeight: 165,
            description: 'Pinterest profile picture (displays as circular)',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '10MB',
            notes: 'Upload at 165×165, displays as circular',
            supportsFlexible: false
        },
        {
            id: 'pinterest-standard',
            displayName: 'Pinterest Standard Pin',
            width: '1000px',
            height: '1500px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.PINTEREST],
            commonUses: [CommonUses.PIN, CommonUses.VERTICAL_IMAGE],
            requiresCrop: true,
            minWidth: 1000,
            minHeight: 1500,
            description: 'Pinterest standard vertical pin',
            aspectRatio: AspectRatios.TWO_THREE,
            maxSize: '10MB',
            notes: 'Height should be 1.2–2.5 times the width for optimal display',
            supportsFlexible: false
        },
        {
            id: 'pinterest-square',
            displayName: 'Pinterest Square Pin',
            width: '1000px',
            height: '1000px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.PINTEREST],
            commonUses: [CommonUses.PIN, CommonUses.INFOGRAPHIC],
            requiresCrop: true,
            minWidth: 1000,
            minHeight: 1000,
            description: 'Pinterest square pin',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '10MB',
            notes: 'Good for infographics and step-by-step guides',
            supportsFlexible: false
        },
        {
            id: 'pinterest-story',
            displayName: 'Pinterest Story Pin',
            width: '1080px',
            height: '1920px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.PINTEREST],
            commonUses: [CommonUses.STORY, CommonUses.VERTICAL_CONTENT],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1920,
            description: 'Pinterest Story pin (full-screen vertical)',
            aspectRatio: AspectRatios.NINE_SIXTEEN,
            maxSize: '10MB',
            notes: 'Similar format to Instagram/Facebook Stories',
            supportsFlexible: false
        },
        // TikTok
        {
            id: 'tiktok-profile',
            displayName: 'TikTok Profile Picture',
            width: '200px',
            height: '200px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.TIKTOK],
            commonUses: [CommonUses.PROFILE, CommonUses.AVATAR],
            requiresCrop: true,
            minWidth: 200,
            minHeight: 200,
            description: 'TikTok profile picture',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '5MB',
            notes: 'Upload at 200×200, minimum 20×20',
            supportsFlexible: false
        },
        {
            id: 'tiktok-video',
            displayName: 'TikTok Video Cover',
            width: '1080px',
            height: '1920px',
            category: TemplateCategories.SOCIAL,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.TIKTOK],
            commonUses: [CommonUses.VIDEO_COVER, CommonUses.THUMBNAIL],
            requiresCrop: true,
            minWidth: 1080,
            minHeight: 1920,
            description: 'TikTok video cover/thumbnail',
            aspectRatio: AspectRatios.NINE_SIXTEEN,
            maxSize: '5MB',
            notes: 'Full-screen vertical format, same as video dimensions',
            supportsFlexible: false
        },
        // === WEB TEMPLATES ===
        {
            id: 'web-hero',
            displayName: 'Hero Banner',
            width: '1920px',
            height: '1080px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG],
            platforms: [PlatformTypes.WEB, PlatformTypes.DESKTOP, PlatformTypes.RESPONSIVE],
            commonUses: [CommonUses.WEBSITE_HERO, CommonUses.LANDING_PAGE],
            requiresCrop: false,
            minWidth: 1920,
            minHeight: 1080,
            description: 'Full-width hero banner for websites',
            aspectRatio: AspectRatios.SIXTEEN_NINE,
            maxSize: '200KB',
            notes: 'Optimize for fast loading, consider responsive breakpoints',
            supportsFlexible: false
        },
        {
            id: 'web-blog',
            displayName: 'Blog Featured Image',
            width: '1200px',
            height: '630px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG],
            platforms: [PlatformTypes.WEB, PlatformTypes.BLOG, PlatformTypes.SOCIAL],
            commonUses: [CommonUses.BLOG_POST, CommonUses.ARTICLE],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 630,
            description: 'Blog post featured image (Open Graph optimal)',
            aspectRatio: AspectRatios.NINETEEN_TEN,
            maxSize: '100KB',
            notes: 'Also works for social media sharing previews',
            supportsFlexible: false
        },
        {
            id: 'web-content',
            displayName: 'Content Image',
            width: '1200px',
            height: 'variable',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.WEB, PlatformTypes.ARTICLE, PlatformTypes.CONTENT],
            commonUses: [CommonUses.ARTICLE_CONTENT, CommonUses.PAGE_CONTENT],
            requiresCrop: false,
            minWidth: 1200,
            minHeight: 600,
            description: 'General content images within articles/pages',
            aspectRatio: AspectRatios.FLEXIBLE,
            maxSize: '150KB',
            supportsFlexible: true,
            notes: 'Flexible height that maintains natural aspect ratio'
        },
        {
            id: 'web-thumb',
            displayName: 'Thumbnail',
            width: '300px',
            height: '300px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG],
            platforms: [PlatformTypes.WEB, PlatformTypes.GALLERY, PlatformTypes.ECOMMERCE],
            commonUses: [CommonUses.GALLERY_THUMBNAIL, CommonUses.PRODUCT_THUMBNAIL],
            requiresCrop: true,
            minWidth: 300,
            minHeight: 300,
            description: 'Small thumbnails for galleries, products, listings',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '30KB',
            notes: 'Keep file size small for grid views',
            supportsFlexible: false
        },
        {
            id: 'web-card',
            displayName: 'Card Image',
            width: '400px',
            height: '300px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG],
            platforms: [PlatformTypes.WEB, PlatformTypes.UI, PlatformTypes.CARDS],
            commonUses: [CommonUses.FEATURE_CARD, CommonUses.PRODUCT_CARD, CommonUses.UI_COMPONENT],
            requiresCrop: true,
            minWidth: 400,
            minHeight: 300,
            description: 'Images for feature cards, product cards, etc.',
            aspectRatio: AspectRatios.FOUR_THREE,
            maxSize: '50KB',
            notes: 'Common card aspect ratio',
            supportsFlexible: false
        },
        {
            id: 'web-og',
            displayName: 'Open Graph Image',
            width: '1200px',
            height: '630px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.WEB, PlatformTypes.SOCIAL],
            commonUses: [CommonUses.SOCIAL_SHARING, CommonUses.LINK_PREVIEW],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 630,
            description: 'Social sharing preview image',
            aspectRatio: AspectRatios.NINETEEN_TEN,
            maxSize: '100KB',
            notes: 'Essential for social media link sharing',
            supportsFlexible: false
        },
        {
            id: 'web-banner-leaderboard',
            displayName: 'Web Banner (Leaderboard)',
            width: '728px',
            height: '90px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.PNG, FileExtensions.JPEG],
            platforms: [PlatformTypes.WEB, PlatformTypes.DESKTOP],
            commonUses: [CommonUses.ADVERTISING, CommonUses.HEADER],
            requiresCrop: false,
            minWidth: 728,
            minHeight: 90,
            description: 'Standard leaderboard banner for websites',
            aspectRatio: '8.09:1',
            maxSize: '50KB',
            notes: 'Standard IAB leaderboard banner size',
            supportsFlexible: false
        },
        {
            id: 'web-banner-skyscraper',
            displayName: 'Web Banner (Skyscraper)',
            width: '160px',
            height: '600px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.PNG, FileExtensions.JPEG],
            platforms: [PlatformTypes.WEB, PlatformTypes.DESKTOP],
            commonUses: [CommonUses.ADVERTISING, CommonUses.SIDEBAR],
            requiresCrop: false,
            minWidth: 160,
            minHeight: 600,
            description: 'Vertical skyscraper banner',
            aspectRatio: '4:15',
            maxSize: '50KB',
            notes: 'Standard IAB skyscraper banner size',
            supportsFlexible: false
        },
        {
            id: 'web-banner-medium',
            displayName: 'Web Banner (Medium Rectangle)',
            width: '300px',
            height: '250px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.PNG, FileExtensions.JPEG],
            platforms: [PlatformTypes.WEB, PlatformTypes.DESKTOP],
            commonUses: [CommonUses.ADVERTISING, CommonUses.CONTENT],
            requiresCrop: false,
            minWidth: 300,
            minHeight: 250,
            description: 'Medium rectangle banner',
            aspectRatio: AspectRatios.SIXTEEN_TEN,
            maxSize: '50KB',
            notes: 'Standard IAB medium rectangle banner size',
            supportsFlexible: false
        },
        {
            id: 'responsive-hero',
            displayName: 'Responsive Hero Image',
            width: '1920px',
            height: '1080px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.AVIF, FileExtensions.JPEG],
            platforms: [PlatformTypes.WEB, PlatformTypes.MOBILE, PlatformTypes.TABLET],
            commonUses: [CommonUses.WEBSITE_HERO, CommonUses.LANDING_PAGE],
            requiresCrop: false,
            minWidth: 1200,
            minHeight: 600,
            description: 'Full-width hero image for responsive designs',
            aspectRatio: AspectRatios.SIXTEEN_NINE,
            maxSize: '200KB',
            notes: 'Responsive hero image for modern websites',
            supportsFlexible: false
        },
        {
            id: 'flexible-web-image',
            displayName: 'Flexible Web Image',
            width: 'variable',
            height: '600px',
            category: TemplateCategories.WEB,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG],
            platforms: [PlatformTypes.WEB, PlatformTypes.RESPONSIVE],
            commonUses: [CommonUses.CONTENT, CommonUses.ARTICLE],
            requiresCrop: false,
            minWidth: 300,
            minHeight: 600,
            description: 'Web image with flexible width',
            aspectRatio: AspectRatios.FLEXIBLE,
            maxSize: '150KB',
            notes: 'Flexible width image for responsive layouts',
            supportsFlexible: true
        },
        // ===== E-COMMERCE TEMPLATES =====
        {
            id: 'ecommerce-product-main',
            displayName: 'Product Image - Main',
            width: '800px',
            height: '800px',
            category: TemplateCategories.ECOMMERCE,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.SHOPIFY, PlatformTypes.WOOCOMMERCE, PlatformTypes.AMAZON, PlatformTypes.EBAY, PlatformTypes.GENERAL],
            commonUses: [CommonUses.PRODUCT_MAIN, CommonUses.CATALOG, CommonUses.THUMBNAIL],
            requiresCrop: true,
            minWidth: 800,
            minHeight: 800,
            description: 'Primary product image for all e-commerce platforms',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '2MB',
            notes: 'Standard square product image compatible with most platforms',
            supportsFlexible: false
        },
        {
            id: 'ecommerce-product-gallery',
            displayName: 'Product Gallery Image',
            width: '1000px',
            height: '1000px',
            category: TemplateCategories.ECOMMERCE,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG],
            platforms: [PlatformTypes.SHOPIFY, PlatformTypes.WOOCOMMERCE, PlatformTypes.EBAY],
            commonUses: [CommonUses.GALLERY, CommonUses.PRODUCT_DETAIL, CommonUses.ALTERNATIVE_VIEW],
            requiresCrop: true,
            minWidth: 1000,
            minHeight: 1000,
            description: 'Additional images for product gallery display',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '2MB',
            notes: 'Square gallery images for product detail pages',
            supportsFlexible: false
        },
        {
            id: 'ecommerce-gallery-high-detail',
            displayName: 'Gallery Image - High Detail',
            width: '2048px',
            height: '2048px',
            category: TemplateCategories.ECOMMERCE,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.SHOPIFY, PlatformTypes.WOOCOMMERCE, PlatformTypes.AMAZON],
            commonUses: [CommonUses.ZOOM_VIEW, CommonUses.HIGH_DETAIL, CommonUses.PRODUCT_INSPECTION],
            requiresCrop: true,
            minWidth: 2048,
            minHeight: 2048,
            description: 'High-resolution product images for zoom and detail views',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '5MB',
            notes: 'High resolution for zoom functionality and detail inspection',
            supportsFlexible: false,
            zoomCompatible: true
        },
        {
            id: 'ecommerce-product-hero',
            displayName: 'Product Hero Image',
            width: '2000px',
            height: '1200px',
            category: TemplateCategories.ECOMMERCE,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG],
            platforms: [PlatformTypes.SHOPIFY, PlatformTypes.WOOCOMMERCE],
            commonUses: [CommonUses.HERO_BANNER, CommonUses.PRODUCT_HEADER, CommonUses.FEATURED_IMAGE],
            requiresCrop: true,
            minWidth: 2000,
            minHeight: 1200,
            description: 'Large hero/banner image for product pages',
            aspectRatio: AspectRatios.FIVE_THREE,
            maxSize: '3MB',
            notes: 'Wide banner image for product page headers',
            supportsFlexible: false
        },
        {
            id: 'ecommerce-product-thumbnail',
            displayName: 'Product Thumbnail',
            width: '300px',
            height: '300px',
            category: TemplateCategories.ECOMMERCE,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG],
            platforms: [PlatformTypes.SHOPIFY, PlatformTypes.WOOCOMMERCE, PlatformTypes.AMAZON, PlatformTypes.EBAY],
            commonUses: [CommonUses.THUMBNAIL, CommonUses.PRODUCT_GRID, CommonUses.QUICK_VIEW],
            requiresCrop: true,
            minWidth: 300,
            minHeight: 300,
            description: 'Small thumbnail images for product grids and carousels',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '500KB',
            notes: 'Small square thumbnails for product listings and grids',
            supportsFlexible: false
        },
        {
            id: 'ecommerce-product-variant',
            displayName: 'Product Variant Image',
            width: '800px',
            height: '800px',
            category: TemplateCategories.ECOMMERCE,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG],
            platforms: [PlatformTypes.SHOPIFY, PlatformTypes.WOOCOMMERCE],
            commonUses: [CommonUses.VARIANT, CommonUses.OPTION, CommonUses.COLOR_SWATCH],
            requiresCrop: true,
            minWidth: 800,
            minHeight: 800,
            description: 'Images for product variants/options',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '1MB',
            notes: 'Square images for product variants (colors, sizes, materials)',
            supportsFlexible: false
        },
        {
            id: 'ecommerce-mobile-optimized',
            displayName: 'Mobile Optimized Product',
            width: '800px',
            height: '800px',
            category: TemplateCategories.ECOMMERCE,
            recommendedFormats: [FileExtensions.WEBP],
            platforms: [PlatformTypes.SHOPIFY, PlatformTypes.WOOCOMMERCE, PlatformTypes.AMAZON, PlatformTypes.EBAY],
            commonUses: [PlatformTypes.MOBILE, PlatformTypes.RESPONSIVE, PlatformTypes.APP],
            requiresCrop: true,
            minWidth: 800,
            minHeight: 800,
            description: 'Product images optimized for mobile shopping',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '1MB',
            notes: 'Optimized for mobile devices with fast loading and clear display',
            supportsFlexible: false,
            mobileFirst: true
        },
        {
            id: 'ecommerce-amazon-standard',
            displayName: 'Amazon Product Image',
            width: '2000px',
            height: '2000px',
            category: TemplateCategories.ECOMMERCE,
            recommendedFormats: [FileExtensions.JPEG, FileExtensions.PNG],
            platforms: [PlatformTypes.AMAZON],
            commonUses: ['amazon-listing', CommonUses.MARKETPLACE],
            requiresCrop: true,
            minWidth: 2000,
            minHeight: 2000,
            description: 'Amazon standard product image requirements',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '10MB',
            notes: 'Amazon requires minimum 1000px, but 2000px recommended for zoom feature',
            supportsFlexible: false,
            amazonGuidelines: 'White background, product fills 85% of image, no watermarks'
        },
        {
            id: 'ecommerce-amazon-lifestyle',
            displayName: 'Amazon Lifestyle Image',
            width: '2000px',
            height: '1500px',
            category: TemplateCategories.ECOMMERCE,
            recommendedFormats: [FileExtensions.JPEG],
            platforms: [PlatformTypes.AMAZON],
            commonUses: [CommonUses.LIFESTYLE, CommonUses.IN_USE, CommonUses.CONTEXT],
            requiresCrop: true,
            minWidth: 2000,
            minHeight: 1500,
            description: 'Amazon lifestyle/in-use product images',
            aspectRatio: AspectRatios.FOUR_THREE,
            maxSize: '10MB',
            notes: 'Amazon allows rectangular images for lifestyle/showing product in use',
            supportsFlexible: false,
            amazonCategory: 'Secondary images can show product in use, features, or scale'
        },
        {
            id: 'ecommerce-amazon-infographic',
            displayName: 'Amazon Infographic',
            width: '1500px',
            height: '2000px',
            category: TemplateCategories.ECOMMERCE,
            recommendedFormats: [FileExtensions.PNG, FileExtensions.JPEG],
            platforms: [PlatformTypes.AMAZON],
            commonUses: [CommonUses.INFOGRAPHIC, 'features', CommonUses.SPECIFICATIONS],
            requiresCrop: true,
            minWidth: 1500,
            minHeight: 2000,
            description: 'Amazon product feature/infographic images',
            aspectRatio: AspectRatios.THREE_FOUR,
            maxSize: '8MB',
            notes: 'Vertical images for Amazon product features and infographics',
            supportsFlexible: false,
            amazonAplus: 'Compatible with Amazon A+ Content for enhanced product descriptions'
        },
        {
            id: 'ecommerce-shopify-standard',
            displayName: 'Shopify Product Image',
            width: '2048px',
            height: '2048px',
            category: TemplateCategories.ECOMMERCE,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG],
            platforms: [PlatformTypes.SHOPIFY],
            commonUses: ['shopify-store', 'online-shop'],
            requiresCrop: true,
            minWidth: 2048,
            minHeight: 2048,
            description: 'Shopify optimized product images',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '20MB',
            notes: 'Shopify supports up to 4472x4472px, but 2048px is optimal for performance',
            supportsFlexible: false,
            shopifyFeatures: 'Supports zoom, multiple variants, and 3D models'
        },
        {
            id: 'ecommerce-shopify-collection',
            displayName: 'Shopify Collection Image',
            width: '1200px',
            height: '600px',
            category: TemplateCategories.ECOMMERCE,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG],
            platforms: [PlatformTypes.SHOPIFY],
            commonUses: [CommonUses.COLLECTION, CommonUses.CATEGORY, CommonUses.DEPARTMENT],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 600,
            description: 'Shopify collection/category banner images',
            aspectRatio: AspectRatios.TWO_ONE,
            maxSize: '2MB',
            notes: 'Wide banner for Shopify collection pages',
            supportsFlexible: false
        },
        {
            id: 'ecommerce-ebay-standard',
            displayName: 'eBay Product Image',
            width: '1600px',
            height: '1600px',
            category: TemplateCategories.ECOMMERCE,
            recommendedFormats: [FileExtensions.JPEG],
            platforms: [PlatformTypes.EBAY],
            commonUses: ['ebay-listing', CommonUses.AUCTION, CommonUses.MARKETPLACE],
            requiresCrop: true,
            minWidth: 1600,
            minHeight: 1600,
            description: 'eBay marketplace product images',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '12MB',
            notes: 'eBay supports up to 9000x9000px, but 1600px is recommended for fast loading',
            supportsFlexible: false,
            ebayGuidelines: 'First image should show product only, subsequent images can include text/features'
        },
        {
            id: 'ecommerce-ebay-gallery-plus',
            displayName: 'eBay Gallery Plus',
            width: '400px',
            height: '400px',
            category: TemplateCategories.ECOMMERCE,
            recommendedFormats: [FileExtensions.JPEG],
            platforms: [PlatformTypes.EBAY],
            commonUses: ['gallery-plus', CommonUses.FEATURED, CommonUses.PROMOTED],
            requiresCrop: true,
            minWidth: 400,
            minHeight: 400,
            description: 'eBay Gallery Plus featured image',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '1MB',
            notes: 'Small square image for eBay Gallery Plus feature',
            supportsFlexible: false,
            ebayFeature: 'Gallery Plus shows larger thumbnail in search results'
        },
        {
            id: 'ecommerce-woocommerce-standard',
            displayName: 'WooCommerce Product Image',
            width: '800px',
            height: '800px',
            category: TemplateCategories.ECOMMERCE,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.JPEG],
            platforms: [PlatformTypes.WOOCOMMERCE],
            commonUses: ['woocommerce-store', 'wordpress-shop'],
            requiresCrop: true,
            minWidth: 800,
            minHeight: 800,
            description: 'WooCommerce WordPress product images',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '2MB',
            notes: 'WooCommerce default size is 800x800px, but themes may require different sizes',
            supportsFlexible: false,
            woocommerceFeatures: 'Supports gallery, variations, and featured images'
        },
        // ===== PRINT TEMPLATES =====
        {
            id: 'print-business-card',
            displayName: 'Business Card',
            width: '3.5in',
            height: '2in',
            category: TemplateCategories.PRINT,
            recommendedFormats: [FileExtensions.PDF, FileExtensions.PNG, FileExtensions.JPEG],
            platforms: [PlatformTypes.PRINT],
            commonUses: [CommonUses.BUSINESS, CommonUses.NETWORKING],
            requiresCrop: true,
            minWidth: 1050,
            minHeight: 600,
            description: 'Standard business card design',
            aspectRatio: '1.75:1',
            maxSize: '2MB',
            notes: 'Standard US business card size',
            supportsFlexible: false
        },
        {
            id: 'print-flyer',
            displayName: 'Flyer',
            width: '8.5in',
            height: '11in',
            category: TemplateCategories.PRINT,
            recommendedFormats: [FileExtensions.PDF, FileExtensions.PNG, FileExtensions.JPEG],
            platforms: [PlatformTypes.PRINT],
            commonUses: [CommonUses.MARKETING, CommonUses.PROMOTION],
            requiresCrop: true,
            minWidth: 2550,
            minHeight: 3300,
            description: 'Standard flyer size',
            aspectRatio: AspectRatios.LETTER_PORTRAIT,
            maxSize: '5MB',
            notes: 'Standard US Letter size flyer',
            supportsFlexible: false
        },
        {
            id: 'print-brochure-trifold',
            displayName: 'Brochure (Tri-fold)',
            width: '8.5in',
            height: '11in',
            category: TemplateCategories.PRINT,
            recommendedFormats: [FileExtensions.PDF, FileExtensions.PNG, FileExtensions.JPEG],
            platforms: [PlatformTypes.PRINT],
            commonUses: [CommonUses.MARKETING, CommonUses.INFORMATION, CommonUses.PROMOTION],
            requiresCrop: true,
            minWidth: 2550,
            minHeight: 3300,
            description: 'Standard tri-fold brochure design',
            aspectRatio: AspectRatios.LETTER_PORTRAIT,
            maxSize: '10MB',
            notes: 'Standard US Letter size with 3 equal panels',
            supportsFlexible: false,
            bleed: '0.125in',
            safeZone: '0.25in'
        },
        {
            id: 'print-brochure-z-fold',
            displayName: 'Brochure (Z-fold)',
            width: '8.5in',
            height: '11in',
            category: TemplateCategories.PRINT,
            recommendedFormats: [FileExtensions.PDF],
            platforms: [PlatformTypes.PRINT],
            commonUses: [CommonUses.MARKETING, CommonUses.CREATIVE, CommonUses.PRESENTATION],
            requiresCrop: true,
            minWidth: 2550,
            minHeight: 3300,
            description: 'Z-fold brochure with staggered panels',
            aspectRatio: AspectRatios.LETTER_PORTRAIT,
            maxSize: '10MB',
            notes: 'Z-fold creates staggered panels for dynamic content',
            supportsFlexible: false,
            bleed: '0.125in',
            safeZone: '0.25in'
        },
        {
            id: 'print-brochure-gatefold',
            displayName: 'Brochure (Gatefold)',
            width: '17in',
            height: '11in',
            category: TemplateCategories.PRINT,
            recommendedFormats: [FileExtensions.PDF],
            platforms: [PlatformTypes.PRINT],
            commonUses: [CommonUses.PREMIUM, CommonUses.PRESENTATION, CommonUses.LUXURY],
            requiresCrop: true,
            minWidth: 5100,
            minHeight: 3300,
            description: 'Gatefold brochure with center opening',
            aspectRatio: AspectRatios.GATEFOLD,
            maxSize: '15MB',
            notes: 'Gatefold opens from the center for dramatic reveals',
            supportsFlexible: false,
            bleed: '0.125in',
            safeZone: '0.25in'
        },
        {
            id: 'print-rack-card',
            displayName: 'Rack Card',
            width: '4in',
            height: '9in',
            category: TemplateCategories.PRINT,
            recommendedFormats: [FileExtensions.PDF, FileExtensions.PNG, FileExtensions.JPEG],
            platforms: [PlatformTypes.PRINT],
            commonUses: [CommonUses.TOURISM, CommonUses.INFORMATION, CommonUses.PROMOTION],
            requiresCrop: true,
            minWidth: 1200,
            minHeight: 2700,
            description: 'Standard rack card for brochure holders',
            aspectRatio: AspectRatios.RACK_CARD_PORTRAIT,
            maxSize: '5MB',
            notes: 'Standard rack card size that fits most brochure displays',
            supportsFlexible: false,
            bleed: '0.125in',
            safeZone: '0.25in'
        },
        {
            id: 'print-rack-card-horizontal',
            displayName: 'Rack Card (Horizontal)',
            width: '9in',
            height: '4in',
            category: TemplateCategories.PRINT,
            recommendedFormats: [FileExtensions.PDF, FileExtensions.PNG, FileExtensions.JPEG],
            platforms: [PlatformTypes.PRINT],
            commonUses: [CommonUses.TOURISM, CommonUses.INFORMATION, CommonUses.ALTERNATIVE],
            requiresCrop: true,
            minWidth: 2700,
            minHeight: 1200,
            description: 'Horizontal rack card alternative',
            aspectRatio: AspectRatios.RACK_CARD_LANDSCAPE,
            maxSize: '5MB',
            notes: 'Horizontal rack card alternative for different displays',
            supportsFlexible: false,
            bleed: '0.125in',
            safeZone: '0.25in'
        },
        {
            id: 'print-newsletter-standard',
            displayName: 'Newsletter (Standard)',
            width: '8.5in',
            height: '11in',
            category: TemplateCategories.PRINT,
            recommendedFormats: [FileExtensions.PDF, FileExtensions.PNG],
            platforms: [PlatformTypes.PRINT],
            commonUses: [CommonUses.CORPORATE, CommonUses.COMMUNICATION, CommonUses.UPDATES],
            requiresCrop: true,
            minWidth: 2550,
            minHeight: 3300,
            description: 'Standard newsletter format',
            aspectRatio: AspectRatios.LETTER_PORTRAIT,
            maxSize: '10MB',
            notes: 'US Letter size newsletter with ample margins',
            supportsFlexible: false,
            bleed: '0.125in',
            safeZone: '0.375in'
        },
        {
            id: 'print-newsletter-tabloid',
            displayName: 'Newsletter (Tabloid)',
            width: '11in',
            height: '17in',
            category: TemplateCategories.PRINT,
            recommendedFormats: [FileExtensions.PDF],
            platforms: [PlatformTypes.PRINT],
            commonUses: [CommonUses.ORGANIZATION, CommonUses.PUBLICATION, CommonUses.NEWSPAPER],
            requiresCrop: true,
            minWidth: 3300,
            minHeight: 5100,
            description: 'Large tabloid newsletter',
            aspectRatio: AspectRatios.TABLOID_PORTRAIT,
            maxSize: '20MB',
            notes: 'Tabloid size for newsletters with multiple columns',
            supportsFlexible: false,
            bleed: '0.25in',
            safeZone: '0.5in'
        },
        {
            id: 'print-poster-small',
            displayName: 'Poster (Small - 11x17)',
            width: '11in',
            height: '17in',
            category: TemplateCategories.PRINT,
            recommendedFormats: [FileExtensions.PDF, FileExtensions.PNG, FileExtensions.JPEG],
            platforms: [PlatformTypes.PRINT],
            commonUses: [CommonUses.ANNOUNCEMENT, CommonUses.INDOOR, CommonUses.EVENT],
            requiresCrop: true,
            minWidth: 3300,
            minHeight: 5100,
            description: 'Small poster size for announcements',
            aspectRatio: AspectRatios.TABLOID_PORTRAIT,
            maxSize: '10MB',
            notes: 'Common small poster size for office announcements',
            supportsFlexible: false,
            bleed: '0.125in',
            safeZone: '0.5in'
        },
        {
            id: 'print-poster-medium',
            displayName: 'Poster (Medium - 18x24)',
            width: '18in',
            height: '24in',
            category: TemplateCategories.PRINT,
            recommendedFormats: [FileExtensions.PDF, FileExtensions.PNG],
            platforms: [PlatformTypes.PRINT],
            commonUses: [CommonUses.CONFERENCE, CommonUses.EXHIBITION, CommonUses.PRESENTATION],
            requiresCrop: true,
            minWidth: 5400,
            minHeight: 7200,
            description: 'Medium poster size for conferences',
            aspectRatio: AspectRatios.THREE_FOUR,
            maxSize: '20MB',
            notes: 'Standard conference poster size',
            supportsFlexible: false,
            bleed: '0.25in',
            safeZone: '1in'
        },
        {
            id: 'print-poster-large',
            displayName: 'Poster (Large - 24x36)',
            width: '24in',
            height: '36in',
            category: TemplateCategories.PRINT,
            recommendedFormats: [FileExtensions.PDF, FileExtensions.PNG],
            platforms: [PlatformTypes.PRINT],
            commonUses: [CommonUses.EVENT, CommonUses.RETAIL, CommonUses.ADVERTISING],
            requiresCrop: true,
            minWidth: 7200,
            minHeight: 10800,
            description: 'Large format poster for major events',
            aspectRatio: AspectRatios.TWO_THREE,
            maxSize: '30MB',
            notes: 'Large format poster for major displays',
            supportsFlexible: false,
            bleed: '0.25in',
            safeZone: '1.5in'
        },
        {
            id: 'print-infographic-portrait',
            displayName: 'Infographic (Portrait)',
            width: '8.5in',
            height: '11in',
            category: TemplateCategories.PRINT,
            recommendedFormats: [FileExtensions.PDF, FileExtensions.PNG],
            platforms: [PlatformTypes.PRINT, PlatformTypes.DIGITAL],
            commonUses: [CommonUses.REPORT, CommonUses.PRESENTATION, CommonUses.EDUCATION],
            requiresCrop: true,
            minWidth: 2550,
            minHeight: 3300,
            description: 'Portrait-oriented infographic',
            aspectRatio: AspectRatios.LETTER_PORTRAIT,
            maxSize: '10MB',
            notes: 'US Letter size infographic for reports',
            supportsFlexible: false,
            bleed: '0in',
            safeZone: '0.5in'
        },
        {
            id: 'print-infographic-landscape',
            displayName: 'Infographic (Landscape)',
            width: '11in',
            height: '8.5in',
            category: TemplateCategories.PRINT,
            recommendedFormats: [FileExtensions.PDF, FileExtensions.PNG],
            platforms: [PlatformTypes.PRINT, PlatformTypes.DIGITAL],
            commonUses: [CommonUses.PRESENTATION, CommonUses.DIGITAL, PlatformTypes.WEB],
            requiresCrop: true,
            minWidth: 3300,
            minHeight: 2550,
            description: 'Landscape-oriented infographic',
            aspectRatio: AspectRatios.LETTER_LANDSCAPE,
            maxSize: '10MB',
            notes: 'Landscape infographic for presentations',
            supportsFlexible: false,
            bleed: '0in',
            safeZone: '0.5in'
        },
        {
            id: 'print-infographic-square',
            displayName: 'Infographic (Square)',
            width: '8.5in',
            height: '8.5in',
            category: TemplateCategories.PRINT,
            recommendedFormats: [FileExtensions.PDF, FileExtensions.PNG],
            platforms: [PlatformTypes.PRINT, PlatformTypes.DIGITAL, PlatformTypes.SOCIAL],
            commonUses: [CommonUses.SOCIAL_MEDIA, CommonUses.DIGITAL, CommonUses.VERSATILE],
            requiresCrop: true,
            minWidth: 2550,
            minHeight: 2550,
            description: 'Square infographic',
            aspectRatio: AspectRatios.SQUARE,
            maxSize: '10MB',
            notes: 'Square format works for both print and social media',
            supportsFlexible: false,
            bleed: '0in',
            safeZone: '0.5in'
        },
        // ===== MOBILE TEMPLATES =====
        {
            id: 'flexible-mobile-hero',
            displayName: 'Flexible Mobile Hero',
            width: 'variable',
            height: 'variable',
            category: TemplateCategories.MOBILE,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.AVIF],
            platforms: [PlatformTypes.MOBILE, PlatformTypes.RESPONSIVE],
            commonUses: [PlatformTypes.MOBILE_APP, 'responsive-web'],
            requiresCrop: false,
            minWidth: 320,
            minHeight: 568,
            description: 'Hero image for mobile devices',
            aspectRatio: AspectRatios.FLEXIBLE,
            maxSize: '200KB',
            notes: 'Flexible hero image for mobile responsive designs',
            supportsFlexible: true
        },
        {
            id: 'small-androids-retina',
            displayName: 'Small/Mid Androids (Retina)',
            width: 'variable',
            height: 'variable',
            category: TemplateCategories.MOBILE,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.AVIF],
            platforms: [PlatformTypes.MOBILE, PlatformTypes.RESPONSIVE],
            commonUses: [PlatformTypes.MOBILE_APP, 'responsive-web'],
            requiresCrop: false,
            minWidth: 720,
            minHeight: 1280,
            description: 'Hero image for small/mid-range Android devices',
            aspectRatio: AspectRatios.NINE_SIXTEEN,
            maxSize: '300KB',
            notes: 'Optimized for Android devices with 2x retina',
            supportsFlexible: true
        },
        {
            id: 'iphone-x-series-retina',
            displayName: 'iPhone X/11/12 Mini (Retina)',
            width: 'variable',
            height: 'variable',
            category: TemplateCategories.MOBILE,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.AVIF],
            platforms: [PlatformTypes.MOBILE, PlatformTypes.RESPONSIVE],
            commonUses: [PlatformTypes.MOBILE_APP, 'responsive-web'],
            requiresCrop: false,
            minWidth: 750,
            minHeight: 1624,
            description: 'Hero image for iPhone X, 11, 12 Mini series',
            aspectRatio: AspectRatios.NINE_SIXTEEN,
            maxSize: '300KB',
            notes: 'Optimized for iPhone X series with 2x retina',
            supportsFlexible: true
        },
        {
            id: 'iphone-plus-retina',
            displayName: 'iPhone XR/11 Pro Max (Retina)',
            width: 'variable',
            height: 'variable',
            category: TemplateCategories.MOBILE,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.AVIF],
            platforms: [PlatformTypes.MOBILE, PlatformTypes.RESPONSIVE],
            commonUses: [PlatformTypes.MOBILE_APP, 'responsive-web'],
            requiresCrop: false,
            minWidth: 828,
            minHeight: 1792,
            description: 'Hero image for larger iPhones',
            aspectRatio: AspectRatios.NINE_SIXTEEN,
            maxSize: '300KB',
            notes: 'Optimized for larger iPhones with 2x retina',
            supportsFlexible: true
        },
        {
            id: 'newer-iphones-retina',
            displayName: 'Newer iPhones 14/16 Pro (Retina)',
            width: 'variable',
            height: 'variable',
            category: TemplateCategories.MOBILE,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.AVIF],
            platforms: [PlatformTypes.MOBILE, PlatformTypes.RESPONSIVE],
            commonUses: [PlatformTypes.MOBILE_APP, 'responsive-web'],
            requiresCrop: false,
            minWidth: 860,
            minHeight: 1864,
            description: 'Hero image for newer iPhones',
            aspectRatio: AspectRatios.NINE_SIXTEEN,
            maxSize: '300KB',
            notes: 'Optimized for newer iPhones with 2x retina',
            supportsFlexible: true
        },
        {
            id: 'pixel-8-7-retina',
            displayName: 'Google Pixel 8/7 (Retina)',
            width: 'variable',
            height: 'variable',
            category: TemplateCategories.MOBILE,
            recommendedFormats: [FileExtensions.WEBP, FileExtensions.AVIF],
            platforms: [PlatformTypes.MOBILE, PlatformTypes.RESPONSIVE],
            commonUses: [PlatformTypes.MOBILE_APP, 'responsive-web'],
            requiresCrop: false,
            minWidth: 824,
            minHeight: 1830,
            description: 'Hero image for Google Pixel devices',
            aspectRatio: AspectRatios.NINE_SIXTEEN,
            maxSize: '300KB',
            notes: 'Optimized for Google Pixel devices with 2x retina',
            supportsFlexible: true
        }
    ],

    // Initialize ALL category arrays dynamically
    ...(() => {
        const categoryArrays = {};

        // Get all unique categories from TemplateCategories object
        const allCategories = new Set([
            ...Object.values(TemplateCategories),
            ...TemplateCategoryKeys
        ]);

        // Initialize empty arrays for all categories
        allCategories.forEach(category => {
            categoryArrays[category] = [];
        });

        return categoryArrays;
    })()
};

// Initialize categorized arrays
LemGendTemplates.ALL.forEach(template => {
    const category = template.category;

    if (category && TemplateCategoryKeys.includes(category)) {
        if (!LemGendTemplates[category]) {
            LemGendTemplates[category] = [];
        }
        LemGendTemplates[category].push(template);
    }

    // Ensure all templates have the supportsFlexible property
    if (template.supportsFlexible === undefined) {
        const widthInfo = template.width?.toString().toLowerCase();
        const heightInfo = template.height?.toString().toLowerCase();
        template.supportsFlexible = widthInfo === 'variable' || heightInfo === 'variable' ||
            widthInfo === 'flexible' || heightInfo === 'flexible' ||
            category === TemplateCategories.FLEXIBLE;
    }
});